### ISSUE TITLE
unity上使用bug挺多了。。。

### ISSUE THREAD

**Issue by ustcltx** [Zheng-Yejian/xyplayer#2]
1. 窗口无法挪动;
2. 第一次使用发出声音后，想试听其他歌之后就无声了。。。但歌是正常播放的，因为进度条在动;
3. unity上桌面歌词显示不断向下移动，然后就跑出桌面，不见了。

**Comment by Zheng-Yejian** [comment]
谢谢反馈，我之前都是在linuxmint 下调整的，没在unity 中测试过。我刚试了一下，除了有些标签显示不完整外，都是正常的呀。要不你先去下载一个我打包好的试试看。

**Comment by Zheng-Yejian** [comment]
安装包在../xyplayer-package
